routes/web.php
<?php

use App\Http\Livewire\ChangePassword;
use App\Http\Livewire\Configuration\Units;
use App\Http\Livewire\Dashboard;
use App\Http\Livewire\ForgotPassword;
use App\Http\Livewire\Inventory\AssignStocks;
use App\Http\Livewire\Inventory\ManageBrands;
use App\Http\Livewire\Inventory\ManageProduct;
use App\Http\Livewire\Inventory\ManageStock;
use App\Http\Livewire\Inventory\ProductHistory;
use App\Http\Livewire\InventoryCategories;
use App\Http\Livewire\InventoryProducts;
use App\Http\Livewire\Login;
use App\Http\Livewire\ManageSales;
use App\Http\Livewire\ManageUsers;
use App\Http\Livewire\Store\ManageStore;
use App\Http\Livewire\ProductStocks;
use App\Http\Livewire\RequestStocks;
use App\Http\Livewire\ResetPassword;
use App\Http\Livewire\Sales\ManageOrder;
use App\Http\Livewire\Sales\ManageOrders;
use App\Http\Livewire\SingleRequestFromStore;
use App\Http\Livewire\StockRequestsFromStore;
use App\Http\Livewire\SingleRequestToStore;
use App\Http\Livewire\StockRequestsToStore;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// TODO: create api routes for orders
// TODO: create api routes for POS
// TODO: create api routes for SALES
// TODO: create api routes for orders
// TODO: create api routes for orders
// TODO: create api routes for orders
// TODO: create api routes for orders
// TODO: create api routes for orders


Route::middleware('guest')->group(function () {
    Route::get('/login', Login::class)->name('login');
});

Route::get('/forgot-password', ForgotPassword::class)->middleware('guest')->name('password.request');
Route::get('/reset-password/{token}', ResetPassword::class)->middleware('guest')->name('password.reset');

// ================================= Auth Routes ===============================================

Route::middleware('auth')->group(function () {
    // =============================== Inventory Routes =======================================

    Route::get('/', Dashboard::class)->name('dashboard');
    Route::get('/change-password', ChangePassword::class)->name('password.change');
    Route::prefix('/inventory')->group(function () {
        Route::get('/categories', InventoryCategories::class)->name('inventory-categories');
        Route::get('/products', InventoryProducts::class)->name('inventory-products');
        Route::get('/manage-product/{slug}', ManageProduct::class)->name('manage-product');
        Route::get('/product-stocks', ProductStocks::class)->name('inventory-product-stocks');
        Route::get('/manage-stock', ManageStock::class)->name('inventory-manage-stock');
        Route::get('/manage-brands', ManageBrands::class)->name('inventory-manage-brands');
        Route::get('/assign-stocks/{slug}', AssignStocks::class)->name('inventory-assign-stocks');
        Route::get('/product-history/{product}', ProductHistory::class)->name('inventory-product-history');
        Route::get('/request-stocks/{product}', RequestStocks::class)->name('inventory-request-stocks');
        Route::get('/stocks-requests-from-store', StockRequestsFromStore::class)->name('inventory-requests-from-store');
        Route::get('/stocks-requests-to-store', StockRequestsToStore::class)->name('inventory-requests-to-store');
        Route::get('/stocks-requests-from-store/{stockRequest}', SingleRequestFromStore::class)->name('single-request-from-store');
        Route::get('/stocks-requests-to-store/{stockRequest}', SingleRequestToStore::class)->name('single-request-to-store');
    });



    Route::prefix('/sales')->group(function () {
        // =============================== Sales Routes =======================================
        Route::get('/manage-sales', ManageSales::class)->name('manage-sales');




        // =============================== Orders Routes =======================================
        Route::get('/orders', ManageOrders::class)->name('manage-orders');
        Route::get('/order/{order}', ManageOrder::class)->name('manage-order');
    });



    // =============================== POS Routes =======================================



    //  // =============================== Auth Routes =======================================


    // =============================== Permission Routes =======================================
    Route::get('/manage-users', ManageUsers::class)->name('manage-users');



    // =============================== Configuration Routes =======================================

    Route::prefix('/configuration')->group(function () {
        Route::get('/units', Units::class)->name('configuration-units');
        Route::get('/manage-stores', ManageStore::class)->name('manage-stores');
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Product extends Model
{
    use HasFactory, HasSlug;

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    public function variations()
    {
        return  $this->hasMany(ProductVariation::class);
    }

    public function getVariationCountAttribute()
    {
        return $this->variations()->count();
    }

    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }

    public function stocks()
    {
        return  $this->hasManyThrough(Stock::class, ProductVariation::class);
    }

    public function histories()
    {
        return $this->hasManyThrough(ProductHistory::class, ProductVariation::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Support\Str;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;


    const ADMIN_ABILITIES = [];
    const MANAGER_ABILITIES = [];
    const USER_ABILITIES = [];




    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'username',
        'phone',
        'old_password',
        'role_id',
        'is_active',
        'email',
        'store_id',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'old_password',
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getFullNameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }

    public function getIsUserAttribute()
    {
        return $this->role && $this->role->name == 'user';
    }


    public function getIsSuperadminAttribute()
    {
        return $this->role && $this->role->name == 'superadmin';
    }


    public function getIsAdminAttribute()
    {
        return $this->role && ($this->role->name === 'superadmin' || $this->role->name === 'admin');
    }

    public function getIsManagerAttribute()
    {
        return $this->role && $this->role->name == 'manager';
    }

    public function getIsHqManagerAttribute()
    {
        return $this->role && $this->role->name === 'manager' && $this->store !== null && $this->store->is_headquarters;
    }

    public function getIsStaffAttribute()
    {
        return $this->role && $this->role->name == 'staff';
    }

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function store()
    {
        return $this->belongsTo(Store::class);
    }

    public function verify()
    {
        $this->markEmailAsVerified();
        $this->verification_token = null;
        $this->save();
    }

    public function generateVerificationToken()
    {
        $this->verification_token = Str::random(8);
        $this->save();
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }
}

app/Http/Livewire/AddUser.php
<?php

namespace App\Http\Livewire;

use App\Models\Store;
use Livewire\Component;
use App\Models\Role;
use App\Models\User;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\Password;

class AddUser extends Component
{
    use AuthorizesRequests;


    public $stores;
    public $roles;
    public $firstName,
        $lastName,
        $username,
        $email,
        $phone,
        $password,
        $password_confirmation,
        $store,
        $role,
        $is_active = false;

    protected $messages = [
        'phone.phone' => 'Invalid phone number',
        'store.prohibited_if' => 'Must be empty if role is User'
    ];

    protected function getRules()
    {
        $allowedRoles = Role::where('name', '<>', 'user')->get()->modelKeys();
        $userRole = Role::whereName('user')->first();

        return [
            'firstName' => 'required|string|max:255',
            'lastName' => 'required|string|max:255',
            'email' => 'required|email|unique:users,email',
            'username' => 'required|unique:users,username|alpha_num',
            'password' => ['required', Password::min(8)->numbers(), 'confirmed'],
            'phone' => ['required', Rule::phone()->country(['NG']), 'unique:users,phone'],
            'is_active' => 'required|boolean',
            'role' => 'required|exists:roles,id',
            'store' => ['nullable', Rule::requiredIf(fn () => in_array($this->role, $allowedRoles)), "prohibited_if:role,{$userRole->id}", 'exists:stores,id']
        ];
    }

    public function render()
    {
        return view('livewire.add-user');
    }

    public function addUser()
    {
        $this->authorize('create', User::class);
        $this->validate();
        $user = User::create([
            'role_id' => $this->role,
            'username' => $this->username,
            'old_password' => bcrypt($this->password),
            'email' => $this->email,
            'first_name' => $this->firstName,
            'last_name' => $this->lastName,
            'is_active' => $this->is_active,
            'store_id' => $this->store ?? null,
            'phone' => $this->phone
        ]);
        $this->resetExcept('stores', 'roles');
        session()->flash('user_added', 'User Added Successfully');
        $this->emitUp('userAdded');
    }
}

app/Http/Livewire/AdminDashboard.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class AdminDashboard extends Component
{
    public $sales;

    public function render()
    {
        return view('livewire.admin-dashboard');
    }

    public function fetchTodaysSales()
    {
    }

    public function fetchYesterdaySales()
    {
    }

    public function fetchTotalSales()
    {
    }

    public function mount()
    {
    }
}

app/Http/Livewire/Categories.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Categories extends Component
{
    public function render()
    {
        return view('livewire.categories');
    }
}

app/Http/Livewire/ChangePassword.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules\Password;
use Livewire\Component;

class ChangePassword extends Component
{
    public $old_password;
    public $password;
    public $password_confirmation;

    protected function getRules()
    {
        $rules = [
            'old_password' => 'required|current_password',
            'password' => ['required', 'confirmed', Password::min(8)->numbers()],
        ];
        return $rules;
    }
    public function render()
    {
        return view('livewire.change-password');
    }

    public function changePassword()
    {
        $this->validate();
        $user = User::find(auth()->id());
        $user->forceFill([
            'password' => Hash::make($this->password),
        ]);
        $user->save();

        session()->flash('password_changed', 'Your password has been changed');
        $this->reset();
    }
}

app/Http/Livewire/Configuration/AddUnit.php
<?php

namespace App\Http\Livewire\Configuration;

use App\Models\Unit;
use Livewire\Component;


class AddUnit extends Component
{
    public $name;

    protected $rules = [
        'name' => 'required|string|max:50|unique:units'
    ];

    public function render()
    {
        return view('livewire.configuration.add-unit');
    }

    public function addUnit()
    {
        $this->validate();
        $unit = new Unit();
        $unit->name = $this->name;
        $unit->save();
        $this->name = null;
        $this->emitUp('unitAdded');
        session()->flash('unit_added', true);
    }
}

app/Http/Livewire/Configuration/Units.php
<?php

namespace App\Http\Livewire\Configuration;

use App\Models\Unit;
use Illuminate\Validation\Rule;
use Livewire\Component;
use Livewire\WithPagination;

class Units extends Component
{
    use WithPagination;

    protected $paginationTheme = 'bootstrap';

    public $selectedUnit;
    public $search;

    protected $listeners = [
        'unitAdded' => 'onUnitAdded'
    ];

    protected function getRules()
    {
        return [
            'selectedUnit.name' => ['required', 'string', 'max:50', Rule::unique('units', 'name')->ignore($this->selectedUnit->name)],
        ];
    }

    public function onUnitAdded()
    {
        $this->resetPage();
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        if (!$this->search) {
            $units = Unit::orderBy('name', 'asc');
        } else {

            $units  = Unit::where('name', 'like', '%' . $this->search . '%')->orderBy('name', 'asc');
        }
        $units = $units->paginate(20);

        return view('livewire.configuration.units', [
            'units' => $units
        ]);
    }


    public function selectUnit(Unit $unit)
    {
        $this->selectedUnit = $unit;
    }


    public function onEdit()
    {
        $this->selectedUnit->save();
        $this->emit('unitEdited');
        session()->flash('unit_edited', 'Unit Edited Succesfully');
    }

    public function onDelete()
    {
        $this->selectedUnit->delete();
        $this->selectedUnit = null;
        $this->emit('unitDeleted');
        session()->flash('unit_deleted', 'Unit Deleted Successfully');
    }
}

app/Http/Livewire/Dashboard.php
<?php

namespace App\Http\Livewire;

use App\Models\Store;
use Livewire\Component;

class Dashboard extends Component
{
    public $user, $store;
    public function render()
    {
        return view('livewire.dashboard');
    }

    public function mount()
    {
        $this->user = auth()->user();
        if (!$this->user->is_admin) {
            $store = Store::with(['sales', 'sales.items'])->where('id', $this->user->store_id)->first();
            $this->store = $store;
        }
    }
}

app/Http/Livewire/ForgotPassword.php
<?php

namespace App\Http\Livewire;

use Illuminate\Support\Facades\Password;

use Livewire\Component;

class ForgotPassword extends Component
{

    public $email;

    protected $rules = [
        'email' => 'required|email|exists:users,email'
    ];


    public function sendResetMail()
    {
        $this->validate();

        $status = Password::sendResetLink(
            ['email' => $this->email]
        );

        if ($status === Password::RESET_LINK_SENT) {
            session()->flash('email_sent', 'The reset link has been sent to your email.');
            $this->reset();
        }
    }


    public function render()
    {
        return view('livewire.forgot-password');
    }
}

app/Http/Livewire/Inventory/AddBrand.php
<?php

namespace App\Http\Livewire\Inventory;

use App\Models\Brand;
use Livewire\Component;

class AddBrand extends Component
{
    public $name;
    public $contact;
    public $address;
    public function render()
    {
        return view('livewire.inventory.add-brand');
    }
    public function addBrand()
    {
        $this->validate([
            'name' => 'required|unique:brands,name',
            'contact' => 'required|string|max:255',
            'address' => 'required'
        ]);
        $brand = new Brand();
        $brand->name = $this->name;
        $brand->contact = $this->contact;
        $brand->address = $this->address;
        $brand->save();
        session()->flash('brand_added', 'Brand added successfully');
        //Add exempted fields
        $this->resetExcept();
    }
}

app/Http/Livewire/Inventory/ManageProductDetails.php
<?php

namespace App\Http\Livewire\Inventory;

use Livewire\Component;

class ManageProductDetails extends Component
{
    public $product;

    public function render()
    {
        return view('livewire.inventory.manage-product-details');
    }
}

app/Http/Livewire/InventoryBrands.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class InventoryBrands extends Component
{
    public function render()
    {
        return view('livewire.inventory-brands');
    }
}

resources/views/livewire/admin-dashboard.blade.php
<div class="container-fluid">
    <div class="row g-2">
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-body row g-0 align-items-center">
                    <div class="col-2">
                        <i class="fa fa-money fa-2x bg-success rounded-circle p-2 text-white"></i>
                    </div>
                    <div class="col-10">
                        <h5 class="card-title text-secondary">Today's Revenue</h5>
                        <h4 class="card-title fw-bold">&#8358;{{ number_format(5000) }}</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-body row g-0 align-items-center">
                    <div class="col-2">
                        <i class="fa fa-money fa-2x bg-info rounded-circle p-2 text-white"></i>
                    </div>
                    <div class="col-10">
                        <h5 class="card-title text-secondary">Monthly Revenue</h5>
                        <h4 class="card-title fw-bold">&#8358;{{ number_format(5000) }}</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-body row g-0 align-items-center">
                    <div class="col-2">
                        <i class="fa fa-money fa-2x bg-warning rounded-circle p-2 text-white"></i>
                    </div>
                    <div class="col-10">
                        <h5 class="card-title text-secondary">Total Revenue</h5>
                        <h4 class="card-title fw-bold">&#8358;{{ number_format(5000) }}</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="table-responsive mt-5">
        <table class="table table-striped text-center">
            <thead>
                <tr>
                    <th>SKU</th>
                    <th>Product Name</th>
                    <th>Variation</th>
                    <th>Store</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>marriage</td>
                    <td>marriage</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

resources/views/livewire/inventory-brands.blade.php
<div>
    {{-- Because she competes with no one, no one can compete with her. --}}
</div>

resources/views/livewire/inventory-products.blade.php
@section('title', 'Manage Products')
<div>
    <livewire:nav-bar />
    <div class="container-fluid">
        <div class="row gy-2 justify-content-center">
            @can('create', App\Models\Product::class)
                <div class="col-md-4">
                    <livewire:inventory.add-product :brands="$brands" :categories="$categories" />
                </div>
            @endcan
            <div class="col-md-8">
                {{-- Product List --}}

                <div class="card">
                    <div class="card-body">
                        <h4 class="mb-2">View Products</h4>
                        <div class="d-flex justify-content-end align-items-center my-2">
                            {{-- Search Products --}}
                            <form>
                                <input type="text" wire:model.debounce.500ms="search"
                                    class="form-control-sm form-control" placeholder="Search Products">
                            </form>
                            <div wire:loading class="ms-2 spinner-border spinner-border-sm text-info" role="status"
                                wire:target="search">

                            </div>
                        </div>

                        <x-alert type="success" message="product_updated" />

                        <div class="table-responsive">
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <tr class="align-center text-center">
                                        <th>#</th>
                                        <th>Product Name</th>
                                        <th>Image</th>
                                        <th>Category</th>
                                        <th>Brand</th>
                                        <th>Variation Count</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($products as $product)
                                        <tr class="text-center">
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $product->name }}</td>
                                            <td>

                                                <img class="img-fluid rounded" style="height: 100px;"
                                                    src="{{ asset('storage/uploads/' . $product->image) }}"
                                                    alt="{{ $product->name }}">


                                            <td>{{ $product->category->name }}</td>
                                            <td>{{ $product->brand->name }}</td>
                                            <td>{{ $product->variation_count }}</td>
                                            <td>
                                                <div class="dropdown">
                                                    <button class="btn btn-secondary btn-sm dropdown-toggle"
                                                        type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
                                                        aria-expanded="false">
                                                        Manage
                                                    </button>
                                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                                        @can('create', App\Models\Product::class)
                                                            <li>
                                                                <a class="dropdown-item" href="#"
                                                                    wire:click="selectProduct({{ $product }})"
                                                                    data-bs-toggle="modal"
                                                                    data-bs-target="#productEditModal">Edit</a>
                                                            </li>
                                                        @endcan
                                                        <li>
                                                            <a class="dropdown-item"
                                                                href="{{ route('manage-product', ['slug' => $product->slug]) }}">Manage
                                                                Product</a>
                                                        </li>
                                                        <li>
                                                            <a class="dropdown-item"
                                                                href="{{ route('inventory-product-history', $product->id) }}">Product
                                                                History</a>
                                                        </li>
                                                        <li>
                                                            <a class="dropdown-item"
                                                                href="{{ route('inventory-request-stocks', $product) }}">Request
                                                                Stocks</a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="7" class="text-center">
                                                @if ($search)
                                                    No products by that search criteria .
                                                @else
                                                    You have no products yet
                                                @endif
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                        <div class="d-flex justify-content-end">
                            {{ $products->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{-- Edit Modal --}}
    <div wire:ignore.self class="modal fade" id="productEditModal" data-bs-backdrop="static" tabindex="-1"
        aria-labelledby="productEditModal" aria-hidden="true">
        <form wire:submit.prevent="editProduct">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Edit Product</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                    </div>
                    @if ($selectedProduct)
                        <div class="modal-body">
                            <div class="mb-2">
                                <label for="" class="form-label">Product Name</label>
                                <input type="text" wire:model="selectedProduct.name"
                                    class="form-control @error('selectedProduct.name') is-invalid @enderror">
                                <x-invalid-feedback field="selectedProduct.name" />

                            </div>
                            <div class="mb-2">
                                <label for="" class="form-label">Product Category</label>
                                <select wire:model="selectedProduct.category_id" name="" id=""
                                    class="form-select @error('selectedProduct.category_id') is-invalid @enderror">
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>

                                <x-invalid-feedback field="selectedProduct.category_id" />
                            </div>
                            <div class="mb-2">
                                <label for="" class="form-label">Product Brand</label>
                                <select wire:model="selectedProduct.brand_id" name="" id=""
                                    class="form-select @error('selectedProduct.brand_id') is-invalid @enderror">
                                    @foreach ($brands as $brand)
                                        <option value="{{ $brand->id }}">{{ $brand->name }}</option>
                                    @endforeach
                                </select>

                                <x-invalid-feedback field="selectedProduct.brand_id" />
                            </div>
                            @if ($image)
                                <img class="img-fluid rounded" src="{{ $image->temporaryUrl() }}"
                                    style="height: 100px" />
                            @else
                                <img class="img-fluid rounded"
                                    src="{{ asset('storage/uploads/' . $selectedProduct->image) }}"
                                    style="height: 100px" />
                            @endif
                            <div class="mb-2">
                                <label for="" class="form-label">Product Category</label>
                                <input wire:model="image" type="file" accept="image/*"
                                    class="form-control  @error('image') is-invalid @enderror">

                                <x-invalid-feedback field="image" />
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    @endif
                </div>
            </div>
        </form>
    </div>
    <script>
        document.addEventListener('livewire:load', () => {
            var productEditModal = new Modal(document.getElementById('productEditModal'))
            Livewire.on('productEdited', () => {
                productEditModal.hide()
            });
        })
    </script>
</div>

resources/views/livewire/stock-accept.blade.php
<div>
    {{-- The Master doesn't talk, he acts. --}}
</div>