routes/web.php
<?php

use App\Http\Livewire\ChangePassword;
use App\Http\Livewire\Configuration\Units;
use App\Http\Livewire\Dashboard;
use App\Http\Livewire\ForgotPassword;
use App\Http\Livewire\Inventory\AssignStocks;
use App\Http\Livewire\Inventory\ManageBrands;
use App\Http\Livewire\Inventory\ManageProduct;
use App\Http\Livewire\Inventory\ManageStock;
use App\Http\Livewire\Inventory\ProductHistory;
use App\Http\Livewire\InventoryCategories;
use App\Http\Livewire\InventoryProducts;
use App\Http\Livewire\Login;
use App\Http\Livewire\ManageSales;
use App\Http\Livewire\ManageUsers;
use App\Http\Livewire\Store\ManageStore;
use App\Http\Livewire\ProductStocks;
use App\Http\Livewire\RequestStocks;
use App\Http\Livewire\ResetPassword;
use App\Http\Livewire\Sales\ManageOrder;
use App\Http\Livewire\Sales\ManageOrders;
use App\Http\Livewire\SingleRequestFromStore;
use App\Http\Livewire\StockRequestsFromStore;
use App\Http\Livewire\SingleRequestToStore;
use App\Http\Livewire\StockRequestsToStore;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// TODO: create api routes for orders
// TODO: create api routes for POS
// TODO: create api routes for SALES
// TODO: create api routes for orders
// TODO: create api routes for orders
// TODO: create api routes for orders
// TODO: create api routes for orders
// TODO: create api routes for orders


Route::middleware('guest')->group(function () {
    Route::get('/login', Login::class)->name('login');
});

Route::get('/forgot-password', ForgotPassword::class)->middleware('guest')->name('password.request');
Route::get('/reset-password/{token}', ResetPassword::class)->middleware('guest')->name('password.reset');

// ================================= Auth Routes ===============================================

Route::middleware('auth')->group(function () {
    // =============================== Inventory Routes =======================================

    Route::get('/', Dashboard::class)->name('dashboard');
    Route::get('/change-password', ChangePassword::class)->name('password.change');
    Route::prefix('/inventory')->group(function () {
        Route::get('/categories', InventoryCategories::class)->name('inventory-categories');
        Route::get('/products', InventoryProducts::class)->name('inventory-products');
        Route::get('/manage-product/{slug}', ManageProduct::class)->name('manage-product');
        Route::get('/product-stocks', ProductStocks::class)->name('inventory-product-stocks');
        Route::get('/manage-stock', ManageStock::class)->name('inventory-manage-stock');
        Route::get('/manage-brands', ManageBrands::class)->name('inventory-manage-brands');
        Route::get('/assign-stocks/{slug}', AssignStocks::class)->name('inventory-assign-stocks');
        Route::get('/product-history/{product}', ProductHistory::class)->name('inventory-product-history');
        Route::get('/request-stocks/{product}', RequestStocks::class)->name('inventory-request-stocks');
        Route::get('/stocks-requests-from-store', StockRequestsFromStore::class)->name('inventory-requests-from-store');
        Route::get('/stocks-requests-to-store', StockRequestsToStore::class)->name('inventory-requests-to-store');
        Route::get('/stocks-requests-from-store/{stockRequest}', SingleRequestFromStore::class)->name('single-request-from-store');
        Route::get('/stocks-requests-to-store/{stockRequest}', SingleRequestToStore::class)->name('single-request-to-store');
    });



    Route::prefix('/sales')->group(function () {
        // =============================== Sales Routes =======================================
        Route::get('/manage-sales', ManageSales::class)->name('manage-sales');




        // =============================== Orders Routes =======================================
        Route::get('/orders', ManageOrders::class)->name('manage-orders');
        Route::get('/order/{order}', ManageOrder::class)->name('manage-order');
    });



    // =============================== POS Routes =======================================



    //  // =============================== Auth Routes =======================================


    // =============================== Permission Routes =======================================
    Route::get('/manage-users', ManageUsers::class)->name('manage-users');



    // =============================== Configuration Routes =======================================

    Route::prefix('/configuration')->group(function () {
        Route::get('/units', Units::class)->name('configuration-units');
        Route::get('/manage-stores', ManageStore::class)->name('manage-stores');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Support\Str;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;


    const ADMIN_ABILITIES = [];
    const MANAGER_ABILITIES = [];
    const USER_ABILITIES = [];




    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'username',
        'phone',
        'old_password',
        'role_id',
        'is_active',
        'email',
        'store_id',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'old_password',
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getFullNameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }

    public function getIsUserAttribute()
    {
        return $this->role && $this->role->name == 'user';
    }


    public function getIsSuperadminAttribute()
    {
        return $this->role && $this->role->name == 'superadmin';
    }


    public function getIsAdminAttribute()
    {
        return $this->role && ($this->role->name === 'superadmin' || $this->role->name === 'admin');
    }

    public function getIsManagerAttribute()
    {
        return $this->role && $this->role->name == 'manager';
    }

    public function getIsHqManagerAttribute()
    {
        return $this->role && $this->role->name === 'manager' && $this->store !== null && $this->store->is_headquarters;
    }

    public function getIsStaffAttribute()
    {
        return $this->role && $this->role->name == 'staff';
    }

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function store()
    {
        return $this->belongsTo(Store::class);
    }

    public function verify()
    {
        $this->markEmailAsVerified();
        $this->verification_token = null;
        $this->save();
    }

    public function generateVerificationToken()
    {
        $this->verification_token = Str::random(8);
        $this->save();
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/SalesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\SaleResource;
use App\Http\Resources\SalesCollection;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Kubis\Services\Sales\SalesServiceInterface;

class SalesController extends Controller
{
    //TODO: List sales
    //TODO: Query and perform operation on sales
    private $saleService;

    public function __construct(SalesServiceInterface $saleService)
    {
        $this->saleService = $saleService;
    }


    public function single(Request $request, $unique_id)
    {
        $sale = $this->saleService->singleSale($unique_id);
        $this->authorize('view', $sale);


        return response()->json(['sale' => new SaleResource($sale)]);
    }


    public function myStoreSales(Request $request)
    {
        $user = $request->user('sanctum');
        $perPage = $request->get('perPage') ?? 10;
        $sales = $this->saleService->storeSales($user->store_id, $perPage);
        return response()->json(
            // $sales

            new SalesCollection($sales)


        );
    }
}

app/Http/Livewire/AddUser.php
<?php

namespace App\Http\Livewire;

use App\Models\Store;
use Livewire\Component;
use App\Models\Role;
use App\Models\User;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\Password;

class AddUser extends Component
{
    use AuthorizesRequests;


    public $stores;
    public $roles;
    public $firstName,
        $lastName,
        $username,
        $email,
        $phone,
        $password,
        $password_confirmation,
        $store,
        $role,
        $is_active = false;

    protected $messages = [
        'phone.phone' => 'Invalid phone number',
        'store.prohibited_if' => 'Must be empty if role is User'
    ];

    protected function getRules()
    {
        $allowedRoles = Role::where('name', '<>', 'user')->get()->modelKeys();
        $userRole = Role::whereName('user')->first();

        return [
            'firstName' => 'required|string|max:255',
            'lastName' => 'required|string|max:255',
            'email' => 'required|email|unique:users,email',
            'username' => 'required|unique:users,username|alpha_num',
            'password' => ['required', Password::min(8)->numbers(), 'confirmed'],
            'phone' => ['required', Rule::phone()->country(['NG']), 'unique:users,phone'],
            'is_active' => 'required|boolean',
            'role' => 'required|exists:roles,id',
            'store' => ['nullable', Rule::requiredIf(fn () => in_array($this->role, $allowedRoles)), "prohibited_if:role,{$userRole->id}", 'exists:stores,id']
        ];
    }

    public function render()
    {
        return view('livewire.add-user');
    }

    public function addUser()
    {
        $this->authorize('create', User::class);
        $this->validate();
        $user = User::create([
            'role_id' => $this->role,
            'username' => $this->username,
            'old_password' => bcrypt($this->password),
            'email' => $this->email,
            'first_name' => $this->firstName,
            'last_name' => $this->lastName,
            'is_active' => $this->is_active,
            'store_id' => $this->store ?? null,
            'phone' => $this->phone
        ]);
        $this->resetExcept('stores', 'roles');
        session()->flash('user_added', 'User Added Successfully');
        $this->emitUp('userAdded');
    }
}

app/Http/Livewire/AdminDashboard.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class AdminDashboard extends Component
{
    public $sales;

    public function render()
    {
        return view('livewire.admin-dashboard');
    }

    public function fetchTodaysSales()
    {
    }

    public function fetchYesterdaySales()
    {
    }

    public function fetchTotalSales()
    {
    }

    public function mount()
    {
    }
}

app/Http/Livewire/Categories.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Categories extends Component
{
    public function render()
    {
        return view('livewire.categories');
    }
}

app/Http/Livewire/ChangePassword.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules\Password;
use Livewire\Component;

class ChangePassword extends Component
{
    public $old_password;
    public $password;
    public $password_confirmation;

    protected function getRules()
    {
        $rules = [
            'old_password' => 'required|current_password',
            'password' => ['required', 'confirmed', Password::min(8)->numbers()],
        ];
        return $rules;
    }
    public function render()
    {
        return view('livewire.change-password');
    }

    public function changePassword()
    {
        $this->validate();
        $user = User::find(auth()->id());
        $user->forceFill([
            'password' => Hash::make($this->password),
        ]);
        $user->save();

        session()->flash('password_changed', 'Your password has been changed');
        $this->reset();
    }
}

app/Http/Livewire/Configuration/AddUnit.php
<?php

namespace App\Http\Livewire\Configuration;

use App\Models\Unit;
use Livewire\Component;


class AddUnit extends Component
{
    public $name;

    protected $rules = [
        'name' => 'required|string|max:50|unique:units'
    ];

    public function render()
    {
        return view('livewire.configuration.add-unit');
    }

    public function addUnit()
    {
        $this->validate();
        $unit = new Unit();
        $unit->name = $this->name;
        $unit->save();
        $this->name = null;
        $this->emitUp('unitAdded');
        session()->flash('unit_added', true);
    }
}

app/Http/Livewire/Configuration/Units.php
<?php

namespace App\Http\Livewire\Configuration;

use App\Models\Unit;
use Illuminate\Validation\Rule;
use Livewire\Component;
use Livewire\WithPagination;

class Units extends Component
{
    use WithPagination;

    protected $paginationTheme = 'bootstrap';

    public $selectedUnit;
    public $search;

    protected $listeners = [
        'unitAdded' => 'onUnitAdded'
    ];

    protected function getRules()
    {
        return [
            'selectedUnit.name' => ['required', 'string', 'max:50', Rule::unique('units', 'name')->ignore($this->selectedUnit->name)],
        ];
    }

    public function onUnitAdded()
    {
        $this->resetPage();
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        if (!$this->search) {
            $units = Unit::orderBy('name', 'asc');
        } else {

            $units  = Unit::where('name', 'like', '%' . $this->search . '%')->orderBy('name', 'asc');
        }
        $units = $units->paginate(20);

        return view('livewire.configuration.units', [
            'units' => $units
        ]);
    }


    public function selectUnit(Unit $unit)
    {
        $this->selectedUnit = $unit;
    }


    public function onEdit()
    {
        $this->selectedUnit->save();
        $this->emit('unitEdited');
        session()->flash('unit_edited', 'Unit Edited Succesfully');
    }

    public function onDelete()
    {
        $this->selectedUnit->delete();
        $this->selectedUnit = null;
        $this->emit('unitDeleted');
        session()->flash('unit_deleted', 'Unit Deleted Successfully');
    }
}

app/Http/Livewire/Dashboard.php
<?php

namespace App\Http\Livewire;

use App\Models\Store;
use Livewire\Component;

class Dashboard extends Component
{
    public $user, $store;
    public function render()
    {
        return view('livewire.dashboard');
    }

    public function mount()
    {
        $this->user = auth()->user();
        if (!$this->user->is_admin) {
            $store = Store::with(['sales', 'sales.items'])->where('id', $this->user->store_id)->first();
            $this->store = $store;
        }
    }
}

app/Http/Livewire/ForgotPassword.php
<?php

namespace App\Http\Livewire;

use Illuminate\Support\Facades\Password;

use Livewire\Component;

class ForgotPassword extends Component
{

    public $email;

    protected $rules = [
        'email' => 'required|email|exists:users,email'
    ];


    public function sendResetMail()
    {
        $this->validate();

        $status = Password::sendResetLink(
            ['email' => $this->email]
        );

        if ($status === Password::RESET_LINK_SENT) {
            session()->flash('email_sent', 'The reset link has been sent to your email.');
            $this->reset();
        }
    }


    public function render()
    {
        return view('livewire.forgot-password');
    }
}

app/Http/Livewire/Inventory/AddBrand.php
<?php

namespace App\Http\Livewire\Inventory;

use App\Models\Brand;
use Livewire\Component;

class AddBrand extends Component
{
    public $name;
    public $contact;
    public $address;
    public function render()
    {
        return view('livewire.inventory.add-brand');
    }
    public function addBrand()
    {
        $this->validate([
            'name' => 'required|unique:brands,name',
            'contact' => 'required|string|max:255',
            'address' => 'required'
        ]);
        $brand = new Brand();
        $brand->name = $this->name;
        $brand->contact = $this->contact;
        $brand->address = $this->address;
        $brand->save();
        session()->flash('brand_added', 'Brand added successfully');
        //Add exempted fields
        $this->resetExcept();
    }
}

app/Http/Livewire/Inventory/ManageProductDetails.php
<?php

namespace App\Http\Livewire\Inventory;

use Livewire\Component;

class ManageProductDetails extends Component
{
    public $product;

    public function render()
    {
        return view('livewire.inventory.manage-product-details');
    }
}

resources/views/livewire/sales/manage-orders.blade.php
@section('title', 'Manage Orders')
<div>
    @livewire('nav-bar')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header h4 text-center">
                        Manage Orders
                    </div>
                    <div class="card-body">
                        <div class="d-flex my-2 justify-content-between">
                            <div>
                                <label for="" class="form-label">Filter</label>
                                <select wire:model="status" id="" class="form-select form-select-sm">
                                    <option value="">All</option>
                                    <option value="pending">Pending</option>
                                    <option value="processsing">Processing</option>
                                    <option value="completed">Completed</option>
                                    <option value="cancelled">Cancelled</option>
                                </select>
                                <label for="" class="form-label">Items Per Page</label>
                                <select wire:model="perPage" id="" class="form-select form-select-sm">

                                    @for ($i = 10; $i <= 100; $i += 10)
                                        <option value="{{ $i }}">{{ $i }}</option>
                                    @endfor
                                </select>
                            </div>
                            <div>
                                <label for="" class="form-label">Search</label>
                                <input wire:model.debounce.500ms="search" type="text"
                                    class="form-control form-control-sm">
                                <label for="" class="form-label">Filter Date</label>
                                <input wire:model="date" type="date" class="form-control form-control-sm">
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table-bordered table text-center">
                                <thead>
                                    <tr>
                                        <th>
                                            Unique ID
                                        </th>
                                        <th>
                                            Customer
                                        </th>
                                        <th>
                                            Items
                                        </th>
                                        <th>
                                            Status
                                        </th>
                                        <th>
                                            Date Created
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($orders as $order)
                                        <tr>
                                            <td>{{ $order->unique_id }}</td>
                                            <td>{{ $order->user->full_name }}</td>
                                            <td>{{ $order->items()->count() }}</td>
                                            <td>
                                                @if ($order->status === 'pending')
                                                    <span
                                                        class="badge bg-warning text-dark">{{ ucfirst($order->status) }}</span>
                                                @elseif($order->status === 'completed')
                                                    <span
                                                        class="badge bg-success">{{ ucfirst($order->status) }}</span>
                                                @elseif($order->status === 'processing')
                                                    <span
                                                        class="badge bg-primary">{{ ucfirst($order->status) }}</span>
                                                @else
                                                    <span class="badge bg-danger">{{ ucfirst($order->status) }}</span>
                                                @endif
                                            </td>
                                            <td>{{ $order->created_at }}</td>
                                            <td>

                                                <button wire:click="selectOrder({{ $order }})"
                                                    class="btn btn-sm btn-primary m-2" data-bs-toggle="modal"
                                                    data-bs-target="#viewOrderModal" role="button">View</button>

                                                <a href="{{ route('manage-order', $order) }}"
                                                    class="btn btn-sm btn-primary m-2">Manage
                                                    Order</a>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="5">No Items</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                        <div class="d-flex justify-content-end">
                            {{ $orders->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <x-modal id="viewOrderModal" size="lg">
        @if ($selectedOrder)
            <table class="table table-striped">
                <tr>
                    <th>Uniqe ID</th>
                    <td> {{ $selectedOrder->unique_id }}</td>
                </tr>
                <tr>
                    <th>Customer</th>
                    <td> {{ $selectedOrder->user->full_name }}</td>
                </tr>
                <tr>
                    <th>Items</th>
                    <td> {{ $selectedOrder->items()->count() }}</td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td>
                        @if ($selectedOrder->status === 'pending')
                            <span class="badge bg-warning text-dark">{{ ucfirst($selectedOrder->status) }}</span>
                        @elseif($selectedOrder->status === 'completed')
                            <span class="badge bg-success">{{ ucfirst($selectedOrder->status) }}</span>
                        @elseif($selectedOrder->status === 'processing')
                            <span class="badge bg-primary">{{ ucfirst($selectedOrder->status) }}</span>
                        @else
                            <span class="badge bg-danger">{{ ucfirst($selectedOrder->status) }}</span>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Date of Order</th>
                    <td>{{ $selectedOrder->created_at }}</td>
                </tr>

            </table>
        @endif
    </x-modal>
    <script>
        window.addEventListener('livewire:load', () => {

        })
    </script>
</div>